In [2]:
import pandas as pd
from Univariate import Univariate
function = Univariate

dataset = pd.read_csv("PreProcess.csv")

quan,qual= function.quanQual(dataset)
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [5]:
dataset[quan].cov()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
sl_no,3870.000000,-52.641355,-58.106028,-40.413645,52.556168,8.102336,2.300514e+05
ssc_p,-52.641355,117.228377,60.348373,42.897137,37.659225,24.535952,9.204679e+04
hsc_p,-58.106028,60.348373,118.755706,34.819820,35.461678,22.555846,1.047953e+05
degree_p,-40.413645,42.897137,34.819820,54.151103,21.929469,17.272020,3.071420e+04
etest_p,52.556168,37.659225,35.461678,21.929469,176.251018,16.886973,1.757669e+05
mba_p,8.102336,24.535952,22.555846,17.272020,16.886973,34.028376,7.104318e+04
salary,230051.401869,92046.789176,104795.266681,30714.199304,175766.850250,71043.180613,6.120326e+09

In [11]:
value = dataset[["degree_p", "etest_p"]].cov()
value1 = dataset[["etest_p", "mba_p"]].cov()
print(value)
print(value1)

           degree_p     etest_p
degree_p  54.151103   21.929469
etest_p   21.929469  176.251018
            etest_p      mba_p
etest_p  176.251018  16.886973
mba_p     16.886973  34.028376

In [12]:
dataset[quan].corr()

             sl_no     ssc_p     hsc_p  degree_p   etest_p     mba_p    salary
sl_no     1.000000 -0.078155 -0.085711 -0.088281  0.063636  0.022327  0.047270
ssc_p    -0.078155  1.000000  0.511472  0.538404  0.261993  0.388478  0.108669
hsc_p    -0.085711  0.511472  1.000000  0.434206  0.245113  0.354823  0.122921
degree_p -0.088281  0.538404  0.434206  1.000000  0.224470  0.402364  0.053352
etest_p   0.063636  0.261993  0.245113  0.224470  1.000000  0.218055  0.169233
mba_p     0.022327  0.388478  0.354823  0.402364  0.218055  1.000000  0.155673
salary    0.047270  0.108669  0.122921  0.053352  0.169233  0.155673  1.000000