In [20]:
import pandas as pd
dataset = pd.read_csv("50_Startups_dataset.csv")
dataset = pd.get_dummies(dataset,dtype=int, drop_first=True)
dataset = dataset.drop(columns="Unnamed: 0")

dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.30,136897.90,471784.20,192261.93,0,1
1,162597.80,151377.69,443898.63,191792.16,0,0
2,153441.61,101145.65,407934.64,191050.49,1,0
3,144372.51,118671.95,383199.72,182902.09,0,1
4,142107.44,91391.87,366168.52,166188.04,1,0
5,131877.00,99814.81,362861.46,156991.22,0,1
6,134615.56,147198.97,127716.92,156122.61,0,0
7,130298.23,145530.16,323876.78,155752.70,1,0
8,120542.62,148719.05,311613.39,152211.87,0,1
9,123334.98,108679.27,304981.72,149760.06,0,0
10,101913.18,110594.21,229161.05,146122.05,1,0
11,100672.06,91790.71,249744.65,144259.50,0,0
12,93863.85,127320.48,249839.54,141585.62,1,0
13,91992.49,135495.17,252665.03,134307.45,0,0
14,119943.34,156547.52,256513.02,132602.75,1,0
15,114523.71,122616.94,261776.33,129917.14,0,1
16,78013.21,121597.65,264346.16,126993.03,0,0
17,94657.26,145077.68,282574.41,125370.47,0,1
18,91749.26,114175.89,294919.67,124267.00,1,0
19,86419.80,153514.21,0.10,122776.96,0,1
20,76253.96,113867.40,298664.57,118474.13,0,0
21,78389.57,153773.53,299737.39,111313.12,0,1
22,73994.66,122782.85,303319.36,110352.35,1,0
23,67532.63,105751.13,304768.83,108734.09,1,0
24,77044.11,99281.44,140574.91,108552.14,0,1
25,64664.81,139553.26,137962.72,107404.44,0,0
26,75328.97,144136.08,134050.17,105733.64,1,0
27,72107.70,127864.65,353183.91,105008.41,0,1
28,66051.62,182645.66,118148.30,103282.48,1,0
29,65605.58,153032.16,107138.48,101004.74,0,1
30,61994.58,115641.38,91131.34,99937.69,1,0
31,61136.48,152702.02,88218.33,97483.66,0,1
32,63408.96,129219.71,46085.35,97427.94,0,0
33,55494.05,103057.59,214634.91,96779.02,1,0
34,46426.17,157694.02,210797.77,96712.90,0,0
35,46014.12,85047.54,205517.74,96479.61,0,1
36,28663.86,127056.31,201126.92,90708.29,1,0
37,44070.05,51283.24,197029.52,89949.24,0,0
38,20229.69,65948.03,185265.20,81229.16,0,1
39,38558.61,82982.19,174999.40,81005.86,0,0
40,28754.43,118546.15,172795.77,78240.01,0,0
41,27893.02,84710.87,164470.81,77798.93,1,0
42,23641.03,96189.73,148001.21,71498.59,0,0
43,15505.83,127382.40,35534.27,69759.08,0,1
44,22177.84,154806.24,28334.82,65200.43,0,0
45,1000.33,124153.14,1904.03,64926.18,0,1
46,1315.56,115816.31,297114.56,49490.85,1,0
47,0.10,135427.02,0.10,42559.83,0,0
48,542.15,51743.25,0.10,35673.51,0,1
49,0.10,116983.90,45173.16,14681.50,0,0

In [21]:
indipendent=dataset[["R&D Spend", "Administration", "Marketing Spend", "State_Florida", "State_New York"]]
dependent=dataset[["Profit"]]

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(indipendent, dependent, test_size=0.3, random_state=0)

X_test

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
28   66051.62       182645.66        118148.30              1               0
11  100672.06        91790.71        249744.65              0               0
10  101913.18       110594.21        229161.05              1               0
41   27893.02        84710.87        164470.81              1               0
2   153441.61       101145.65        407934.64              1               0
27   72107.70       127864.65        353183.91              0               1
38   20229.69        65948.03        185265.20              0               1
31   61136.48       152702.02         88218.33              0               1
22   73994.66       122782.85        303319.36              1               0
4   142107.44        91391.87        366168.52              1               0
33   55494.05       103057.59        214634.91              1               0
35   46014.12        85047.54        205517.74              0               1
26   75328.97       144136.08        134050.17              1               0
34   46426.17       157694.02        210797.77              0               0
18   91749.26       114175.89        294919.67              1               0

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [24]:
scy=StandardScaler()
y_train= scy.fit_transform(y_train)
y_test= scy.transform(y_test)

In [25]:
from sklearn.svm import SVR
regrossor= SVR(kernel="rbf", C=1000)
regrossor.fit(X_train, y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [26]:
regrossor._intercept_

array([-0.18206016])

In [27]:
regrossor.n_support_

array([26], dtype=int32)

In [28]:
regrossor.support_

array([ 0,  1,  3,  5,  6,  7,  9, 10, 11, 12, 17, 18, 19, 20, 21, 22, 23,
       25, 26, 27, 28, 29, 30, 31, 33, 34], dtype=int32)

In [29]:
y_predict=regrossor.predict(X_test)

In [30]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_predict)
r2_score

0.6349909314559969

In [31]:
import pickle
filename="final_model_both.sav"

In [32]:
pickle.dump(regrossor, open(filename, "wb"))

In [33]:
with open("sclarX.pkl", "wb") as file:
    pickle.dump(sc, file)

print("Scaler saved successfully")

Scaler saved successfully

In [34]:
with open("sclarY.pkl", "wb") as file:
    pickle.dump(scy, file)

print("Scaler saved successfully")

Scaler saved successfully

In [35]:
preinput = sc.transform([[13000, 12000, 4000, 1, 0]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [36]:
preinput

array([[-1.22774842, -4.33835773, -1.50744333,  2.        , -0.76870611]])

In [37]:
load_model=pickle.load(open(filename, "rb"))

In [38]:
result = load_model.predict(preinput)
final_result = scy.inverse_transform([result])

final_result = round(final_result[0][0], 2)

print(final_result)

95798.04